# Generated by Django 4.2.5 on 2023-09-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aliases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('the_alias', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='supaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supa_id', models.UUIDField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
