# Generated by Django 4.2.5 on 2023-09-17 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliases',
            name='alias_owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='alias.supaprofile'),
            preserve_default=False,
        ),
    ]
