# Generated by Django 4.2.5 on 2023-09-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alias', '0006_aliases_created_on_lockandkey_created_on_sendmoney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliases',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lockandkey',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sendmoney',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
