# Generated by Django 4.2.5 on 2023-09-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alias', '0009_rename_sendmoney_aliastransactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliastransactions',
            name='sender',
            field=models.CharField(),
        ),
    ]
