# Generated by Django 4.2.5 on 2023-09-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alias', '0010_alter_aliastransactions_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliases',
            name='created_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='aliastransactions',
            name='sent_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lockandkey',
            name='created_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='supaprofile',
            name='first_login_at',
            field=models.DateTimeField(),
        ),
    ]
