# Generated by Django 4.2.5 on 2023-09-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alias', '0012_verifieddigits'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliastransactions',
            name='transaction_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aliases',
            name='desired_alias',
            field=models.CharField(db_index=True, unique=True),
        ),
    ]
