# Generated by Django 4.2.5 on 2023-09-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alias', '0013_aliastransactions_transaction_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliastransactions',
            name='transaction_identifier',
            field=models.CharField(default='wc5f2_97ef1ea3a82e752b'),
        ),
    ]
