# Generated by Django 4.2.5 on 2023-09-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alias', '0014_aliastransactions_transaction_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliases',
            name='desired_alias',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='aliases',
            name='num_cipher',
            field=models.BinaryField(default=None),
        ),
        migrations.AlterField(
            model_name='aliastransactions',
            name='receiver',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aliastransactions',
            name='sender',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aliastransactions',
            name='transaction_identifier',
            field=models.CharField(default='wc5f2_97ef1ea3a82e752b', max_length=255),
        ),
        migrations.AlterField(
            model_name='lockandkey',
            name='designated_alias',
            field=models.CharField(default='alias0', max_length=255, unique=True),
        ),
    ]
